
-- Ajout de 10 nouvelles perles (avec slugs uniques)
INSERT INTO public.products (name, slug, category, description, price, images, badge, in_stock, variants) VALUES
('Perle Akoya Ronde Parfaite 9mm', 'perle-akoya-ronde-parfaite-9mm', 'pearls', 'Perle Akoya japonaise de qualité exceptionnelle, 9mm de diamètre. Lustre miroir et orient remarquable. Certification GIA incluse.', 890, ARRAY['/src/assets/products/pearl-round-aaa.jpg'], 'new', true, '{"qualities": ["AAA", "AAA+"], "diameters": ["9mm"]}'),
('Perle Dorée Champagne Australie', 'perle-doree-champagne-australie', 'pearls', 'Magnifique perle dorée champagne des mers du Sud australiennes. 12mm, lustre satiné exceptionnel.', 1450, ARRAY['/src/assets/products/pearl-gold-1.jpg'], 'bestseller', true, '{"qualities": ["AA", "AAA"], "diameters": ["12mm", "13mm"]}'),
('Perle Tahiti Reflets Peacock', 'perle-tahiti-reflets-peacock', 'pearls', 'Perle de Tahiti aux reflets paon iridescents. 10mm de diamètre, qualité gemme certifiée.', 1280, ARRAY['/src/assets/products/pearl-tahiti-round-1.jpg'], NULL, true, '{"qualities": ["AA", "AAA"], "diameters": ["10mm", "11mm"]}'),
('Perle Baroque Organique Unique', 'perle-baroque-organique-unique', 'pearls', 'Perle baroque naturelle aux formes organiques uniques. Reflets multicolores, pièce unique.', 620, ARRAY['/src/assets/products/pearl-baroque-1.jpg'], 'new', true, '{"qualities": ["A", "AA"], "diameters": ["14-16mm"]}'),
('Lot 12 Perles Créations Premium', 'lot-12-perles-creations-premium', 'pearls', 'Ensemble de 12 perles assorties de haute qualité pour créations personnalisées. Couleurs et tailles variées.', 1890, ARRAY['/src/assets/products/pearl-set-matched-1.jpg'], NULL, true, '{"qualities": ["AAA"]}'),
('Perle Conque Rose Naturelle Rare', 'perle-conque-rose-naturelle-rare', 'pearls', 'Perle de conque naturelle rose, extrêmement rare. Forme ovale parfaite, 8mm. Certificat d''authenticité.', 3200, ARRAY['/src/assets/products/pearl-drop-1.jpg'], 'bestseller', true, '{"qualities": ["Gem"], "diameters": ["8mm"]}'),
('Perle Melo Orange Vietnam', 'perle-melo-orange-vietnam', 'pearls', 'Perle Melo naturelle orange intense, provenance Vietnam. Rareté exceptionnelle, 9mm.', 4500, ARRAY['/src/assets/products/pearl-exceptional-1.jpg'], 'new', true, '{"qualities": ["Gem"], "diameters": ["9mm"]}'),
('Duo Perles Akoya Identiques 8mm', 'duo-perles-akoya-identiques-8mm', 'pearls', 'Paire parfaitement assortie de perles Akoya 8mm. Idéale pour boucles d''oreilles haut de gamme.', 780, ARRAY['/src/assets/products/pearl-pair-1.jpg'], NULL, true, '{"qualities": ["AAA"], "diameters": ["8mm"]}'),
('Perle Keshi Libre Dorée', 'perle-keshi-libre-doree', 'pearls', 'Perle Keshi naturelle aux reflets dorés intenses. Forme libre artistique, lustre exceptionnel.', 340, ARRAY['/src/assets/products/pearl-keshi-1.jpg'], 'new', true, '{"qualities": ["AA", "AAA"]}'),
('Perle Bouton Nacre Blanche', 'perle-bouton-nacre-blanche', 'pearls', 'Perle bouton blanche d''eau douce, 7mm. Parfaite pour pendentifs et bagues. Lustre nacré intense.', 180, ARRAY['/src/assets/products/pearl-button-1.jpg'], NULL, true, '{"qualities": ["AA", "AAA"], "diameters": ["7mm", "8mm"]}'),

-- Ajout de 10 nouveaux bracelets (avec slugs uniques)
('Bracelet Tahiti Triple Rang Luxe', 'bracelet-tahiti-triple-rang-luxe', 'bracelets', 'Bracelet trois rangs de perles de Tahiti 8-9mm. Fermoir or blanc 18 carats serti de diamants.', 3890, ARRAY['/src/assets/products/bracelet-multi-pearl-1.jpg'], 'bestseller', true, '{"sizes": ["16cm", "17cm", "18cm"]}'),
('Bracelet Jonc Moderne Akoya', 'bracelet-jonc-moderne-akoya', 'bracelets', 'Jonc rigide en or jaune 18 carats avec perle Akoya 9mm. Design épuré et moderne.', 1290, ARRAY['/src/assets/products/bracelet-bangle-1.jpg'], 'new', true, '{"sizes": ["S", "M", "L"]}'),
('Bracelet Cuir Italien Perle', 'bracelet-cuir-italien-perle', 'bracelets', 'Bracelet en cuir italien tressé avec perle baroque centrale. Style bohème chic.', 280, ARRAY['/src/assets/products/bracelet-leather-1.jpg'], NULL, true, '{"sizes": ["17cm", "18cm", "19cm", "20cm"]}'),
('Bracelet Charms Perles Roses', 'bracelet-charms-perles-roses', 'bracelets', 'Bracelet chaîne or rose avec charms en perles d''eau douce. 5 perles de couleurs variées.', 590, ARRAY['/src/assets/products/bracelet-charm-1.jpg'], 'bestseller', true, '{"sizes": ["16cm", "17cm", "18cm"]}'),
('Bracelet Manchette Or Blanc Tressé', 'bracelet-manchette-or-blanc-tresse', 'bracelets', 'Manchette en or blanc tissé avec perles Akoya 6mm. Pièce statement élégante.', 2450, ARRAY['/src/assets/products/bracelet-cuff-1.jpg'], NULL, true, '{"sizes": ["S", "M"]}'),
('Bracelet Soie Tressée Perles', 'bracelet-soie-tressee-perles', 'bracelets', 'Bracelet en fil de soie tressé avec perles d''eau douce pastel. Légèreté et féminité.', 195, ARRAY['/src/assets/products/bracelet-silk-1.jpg'], 'new', true, '{"sizes": ["16cm", "17cm", "18cm"]}'),
('Bracelet Tennis Luxe Perles', 'bracelet-tennis-luxe-perles', 'bracelets', 'Bracelet tennis alternant perles Akoya et diamants. Or blanc 18 carats, 1.5 carats total.', 4890, ARRAY['/src/assets/products/bracelet-diamonds-1.jpg'], 'new', true, '{"sizes": ["17cm", "18cm"]}'),
('Bracelet Deux Rangs Mers Sud', 'bracelet-deux-rangs-mers-sud', 'bracelets', 'Double rang de perles des mers du Sud dorées 9-10mm. Fermoir fleur en or jaune.', 2890, ARRAY['/src/assets/products/bracelet-double-strand-1.jpg'], NULL, true, '{"sizes": ["17cm", "18cm", "19cm"]}'),
('Bracelet Classique Eau Douce', 'bracelet-classique-eau-douce', 'bracelets', 'Bracelet rang complet de perles d''eau douce blanches 7mm. Fermoir or jaune 14 carats.', 420, ARRAY['/src/assets/products/bracelet-full-strand-1.jpg'], 'bestseller', true, '{"sizes": ["17cm", "18cm", "19cm"]}'),
('Bracelet Chaînette Fine Perle', 'bracelet-chainette-fine-perle', 'bracelets', 'Bracelet chaîne fine or jaune 18 carats avec perle Akoya centrale 8mm. Minimaliste et raffiné.', 490, ARRAY['/src/assets/products/bracelet-gold-pearl-1.jpg'], 'new', true, '{"sizes": ["16cm", "17cm", "18cm"]}'),

-- Ajout de 10 nouveaux colliers (avec slugs uniques)
('Collier Lariat Moderne Akoya', 'collier-lariat-moderne-akoya', 'necklaces', 'Collier lariat avec cascade de perles Akoya. Longueur ajustable, style versatile moderne.', 1680, ARRAY['/src/assets/products/necklace-lariat-1.jpg'], 'new', true, '{"sizes": ["80cm"]}'),
('Collier Choker Velours Tahiti', 'collier-choker-velours-tahiti', 'necklaces', 'Ras de cou en velours noir avec perle de Tahiti centrale 12mm. Élégance dramatique.', 890, ARRAY['/src/assets/products/necklace-choker-1.jpg'], 'bestseller', true, '{"sizes": ["35cm", "38cm", "40cm"]}'),
('Collier Opéra 4 Rangs Perles', 'collier-opera-4-rangs-perles', 'necklaces', 'Collier quatre rangs de perles d''eau douce, longueur opéra. Fermoir vintage en or.', 1890, ARRAY['/src/assets/products/necklace-multi-strand-1.jpg'], NULL, true, '{"sizes": ["75cm"]}'),
('Collier Station 7 Perles Akoya', 'collier-station-7-perles-akoya', 'necklaces', 'Collier chaîne or avec perles Akoya espacées. 7 perles de 7mm, élégance discrète.', 980, ARRAY['/src/assets/products/necklace-station-1.jpg'], 'new', true, '{"sizes": ["42cm", "45cm"]}'),
('Collier Princesse Perles Dégradé', 'collier-princesse-perles-degrade', 'necklaces', 'Collier princesse avec perles en dégradé de taille 6-9mm. Effet visuel spectaculaire.', 1450, ARRAY['/src/assets/products/necklace-princess-1.jpg'], NULL, true, '{"sizes": ["45cm"]}'),
('Collier Gala Diamants Mers Sud', 'collier-gala-diamants-mers-sud', 'necklaces', 'Collier col en or blanc serti de diamants avec perles des mers du Sud. Pièce de gala.', 8900, ARRAY['/src/assets/products/necklace-collar-diamonds-1.jpg'], 'bestseller', true, '{"sizes": ["38cm", "40cm"]}'),
('Collier Cuir Naturel Baroque XL', 'collier-cuir-naturel-baroque-xl', 'necklaces', 'Collier en cuir naturel avec grande perle baroque centrale. Style audacieux et unique.', 380, ARRAY['/src/assets/products/necklace-leather-1.jpg'], NULL, true, '{"sizes": ["45cm", "50cm"]}'),
('Collier Pendentif Akoya Classic', 'collier-pendentif-akoya-classic', 'necklaces', 'Pendentif perle Akoya 8mm sur chaîne or blanc fine. Classique intemporel.', 490, ARRAY['/src/assets/products/necklace-pendant-1.jpg'], 'bestseller', true, '{"sizes": ["40cm", "42cm", "45cm"]}'),
('Collier Rang Premium Akoya AAA', 'collier-rang-premium-akoya-aaa', 'necklaces', 'Collier rang simple de perles Akoya AAA 7.5mm. Fermoir sphère or blanc.', 2890, ARRAY['/src/assets/products/necklace-strand-1.jpg'], NULL, true, '{"sizes": ["40cm", "45cm", "50cm"]}'),
('Sautoir 90cm Mers du Sud Bicolor', 'sautoir-90cm-mers-sud-bicolor', 'necklaces', 'Sautoir de perles des mers du Sud dorées et blanches alternées. 90cm de luxe.', 5890, ARRAY['/src/assets/products/necklace-sautoir-1.jpg'], 'new', true, '{"sizes": ["90cm"]}'),

-- Ajout de 10 nouvelles bagues (avec slugs uniques)
('Bague Solitaire Classic Akoya', 'bague-solitaire-classic-akoya', 'rings', 'Bague solitaire classique avec perle Akoya 8mm montée sur or jaune 18 carats.', 590, ARRAY['/src/assets/products/ring-solitaire-1.jpg'], 'new', true, '{"sizes": ["48", "50", "52", "54", "56"]}'),
('Bague Halo Brillants Tahiti', 'bague-halo-brillants-tahiti', 'rings', 'Bague perle de Tahiti 10mm entourée d''un halo de diamants. Or blanc 18 carats.', 2890, ARRAY['/src/assets/products/ring-halo-1.jpg'], 'bestseller', true, '{"sizes": ["50", "52", "54", "56"]}'),
('Bague Cocktail Baroque Rosé', 'bague-cocktail-baroque-rose', 'rings', 'Bague cocktail avec perle baroque naturelle. Monture or rose sculptée artisanalement.', 890, ARRAY['/src/assets/products/ring-vintage-1.jpg'], NULL, true, '{"sizes": ["50", "52", "54", "56", "58"]}'),
('Bague Asymétrique Design Akoya', 'bague-asymetrique-design-akoya', 'rings', 'Bague design asymétrique avec perle Akoya décentrée. Or jaune brossé contemporain.', 780, ARRAY['/src/assets/products/ring-modern-1.jpg'], 'new', true, '{"sizes": ["48", "50", "52", "54", "56"]}'),
('Bague Trio Perles Eau Douce', 'bague-trio-perles-eau-douce', 'rings', 'Bague avec trois perles d''eau douce alignées sur or blanc. Élégance minimaliste.', 490, ARRAY['/src/assets/products/ring-three-stone-1.jpg'], NULL, true, '{"sizes": ["50", "52", "54", "56"]}'),
('Bague Bypass Perle Mers Sud Gold', 'bague-bypass-perle-mers-sud-gold', 'rings', 'Bague bypass en or jaune avec perle des mers du Sud 11mm. Design fluide et moderne.', 1680, ARRAY['/src/assets/products/ring-bypass-1.jpg'], 'bestseller', true, '{"sizes": ["50", "52", "54", "56"]}'),
('Bague Pavé Diamants Akoya', 'bague-pave-diamants-akoya', 'rings', 'Bague perle Akoya avec anneau pavé de diamants. 0.5 carat total, or blanc 18 carats.', 1890, ARRAY['/src/assets/products/ring-pearl-diamonds-1.jpg'], NULL, true, '{"sizes": ["48", "50", "52", "54", "56"]}'),
('Bague Empilable Délicate Perle', 'bague-empilable-delicate-perle', 'rings', 'Bague fine empilable avec petite perle 5mm. Parfaite seule ou en accumulation.', 290, ARRAY['/src/assets/products/ring-stackable-1.jpg'], 'new', true, '{"sizes": ["48", "50", "52", "54", "56", "58"]}'),
('Bague Or Martelé Artisanal Baroque', 'bague-or-martele-artisanal-baroque', 'rings', 'Bague or jaune martelé artisanal avec perle baroque. Pièce unique, style organique.', 680, ARRAY['/src/assets/products/ring-hammered-1.jpg'], NULL, true, '{"sizes": ["50", "52", "54", "56"]}'),
('Bague Ouverte Duo Perles Akoya', 'bague-ouverte-duo-perles-akoya', 'rings', 'Bague ouverte ajustable avec deux perles Akoya aux extrémités. Design audacieux.', 720, ARRAY['/src/assets/products/ring-open-band-1.jpg'], NULL, true, '{"sizes": ["Ajustable"]}'),

-- Ajout de 10 nouveaux accessoires (avec slugs uniques)
('Broche Art Nouveau Fleur Perle', 'broche-art-nouveau-fleur-perle', 'other', 'Broche inspiration Art Nouveau avec perle centrale et pétales en or émaillé. Pièce de collection.', 1890, ARRAY['/src/assets/products/brooch-1.jpg'], 'new', true, NULL),
('Pendentif Halo Diamants Akoya 9mm', 'pendentif-halo-diamants-akoya-9mm', 'other', 'Pendentif perle Akoya 9mm entourée de diamants. Bélière sertie, or blanc 18 carats.', 1290, ARRAY['/src/assets/products/pendant-diamond-halo-1.jpg'], 'bestseller', true, NULL),
('Boucles Chandelier Cascade Perles', 'boucles-chandelier-cascade-perles', 'other', 'Boucles d''oreilles chandelier avec cascade de perles d''eau douce. Glamour hollywoodien.', 890, ARRAY['/src/assets/products/earrings-chandelier-1.jpg'], 'new', true, NULL),
('Ear Cuff Design Perle Suspendue', 'ear-cuff-design-perle-suspendue', 'other', 'Ear cuff en or jaune avec perle Akoya suspendue. Porté sans perçage, style edgy.', 390, ARRAY['/src/assets/products/ear-cuff-1.jpg'], 'new', true, NULL),
('Épingle Cheveux Mariée Perle', 'epingle-cheveux-mariee-perle', 'other', 'Épingle à cheveux dorée ornée de perles d''eau douce. Accessoire de mariée idéal.', 180, ARRAY['/src/assets/products/hair-pin-1.jpg'], NULL, true, NULL),
('Parure 3 Pièces Akoya Assortie', 'parure-3-pieces-akoya-assortie', 'other', 'Parure complète: collier, bracelet et boucles d''oreilles en perles Akoya 7mm assorties.', 3890, ARRAY['/src/assets/products/set-complete-1.jpg'], 'bestseller', true, NULL),
('Créoles Or 18K Perles Enfilées', 'creoles-or-18k-perles-enfilees', 'other', 'Créoles en or jaune 18 carats avec perles d''eau douce enfilées. Diamètre 3cm.', 590, ARRAY['/src/assets/products/earrings-hoops-1.jpg'], NULL, true, NULL),
('Pendentif Minimaliste Or Rose', 'pendentif-minimaliste-or-rose', 'other', 'Pendentif minimaliste perle Akoya 7mm sur bélière or rose. Chaîne non incluse.', 290, ARRAY['/src/assets/products/pendant-simple-1.jpg'], NULL, true, NULL),
('Puces Classic Akoya Or Blanc', 'puces-classic-akoya-or-blanc', 'other', 'Puces d''oreilles classiques perles Akoya 7mm. Fermoirs poussettes or blanc 18 carats.', 390, ARRAY['/src/assets/products/earrings-stud-1.jpg'], 'bestseller', true, NULL),
('Pendantes Tahiti Chaînettes Mobiles', 'pendantes-tahiti-chainettes-mobiles', 'other', 'Boucles pendantes avec perles de Tahiti 9mm sur chaînettes or blanc. Mouvement élégant.', 1290, ARRAY['/src/assets/products/earrings-drop-1.jpg'], 'new', true, NULL);
